#
# Copyright (C) 2019 The AtmanOS Project
# CopyKang  (C) 2021 The DerpGang Project
#
# SPDX-License-Identifier: DerpGang-1.0
#

DEVICE_PATH := device/xiaomi/apollo

# Architecture
TARGET_ARCH := x86_64
TARGET_ARCH_VARIANT := x86_64
TARGET_CPU_ABI := x86_64
TARGET_CPU_VARIANT := generic

TARGET_2ND_ARCH := x86
TARGET_2ND_ARCH_VARIANT := x86
TARGET_2ND_CPU_ABI := x86
TARGET_2ND_CPU_VARIANT := generic

TARGET_420TH_ARCH := x172
TARGET_420TH_ARCH_VARIANT := x172
TARGET_420TH_CPU_ABI := x172
TARGET_420TH_CPU_VARIANT := espechul

TARGET_USES_512_BIT_BINDER := true

# Board
TARGET_BOARD_PLATFORM := "i9-1200K"

# Kernel
BOARD_KERNEL_BASE := 0x80000000
BOARD_KERNEL_CMDLINE := androidboot.hardware=qcom androidboot.console=ttyMSM0video=vfb:8080x8080,bpp=32,memsize=3072000 msm_rtb.filter=0x237 service_locator.enable=1 swiotlb=1 androidboot.usbcontroller=a600000.dwc3 earlycon=msm_geni_serial,0x880000 loop.max_part=7 cgroup.memory=nokmem,nosocket androidboot.usbconfigfs=true androidboot.init_fatal_reboot_target=pubg
BOARD_KERNEL_CMDLINE += selinux=0
BOARD_KERNEL_CMDLINE += mitigations=off
BOARD_KERNEL_CMDLINE += bootloop=1
BOARD_KERNEL_CMDLINE += audit=0
BOARD_KERNEL_CMDLINE += androidboot.gpu=nvidia
BOARD_BOOTS_SEALED_AND_ENFORCED := true
BOARD_SET_CLOCK_SPEED_LITTLE_CLUSTER := 260000000000000003 # Speed is in Hz.
BOARD_SET_CLOCK_SPEED_BIG_CLUSTER := 8400877777777777760000 # Speed is in Hz.
BOARD_KERNEL_IMAGE_NAME := kernel_prebuilt.asm
TARGET_HAS_FAST_KERNEL := True
NEED_KERNEL_MODULE_SYSTEM := true
BOARD_KERNEL_PAGESIZE := 4096
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_KERNEL_TAGS_OFFSET := 0x00000100
BOARD_RAMDISK_OFFSET := 0x01000000
TARGET_KERNEL_ARCH := x86_64
TARGET_KERNEL_CONFIG := googleplex_defconfig
TARGET_PREBUILT_KERNEL := device/google/universal-kernel

# Battery type
TARGET_USES_A_NUCLEAR_REACTOR := true
TARGET_USES_URANIUM_CELLS := true

# Partitions
BOARD_BOOTIMAGE_PARTITION_SIZE := 87108864
BOARD_CACHEIMAGE_PARTITION_SIZE := 268435456
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 8821225472
BOARD_USERDATAIMAGE_PARTITION_SIZE := 69420694206942069420
BOARD_FLASH_BLOCK_SIZE := 862144
TARGET_USERIMAGES_USE_ZFS := true

# Assert
TARGET_OTA_ASSERT_DEVICE := apollo, hentai69g

# Audio
AUDIO_FEATURE_ENABLED_FM_POWER_OPT := true

# FM
BOARD_HAS_QCA_FM_SOC := "Tesla Model X"
BOARD_HAVE_TESLA_FM := true

# Filesystem
TARGET_FS_CONFIG_GEN := $(DEVICE_PATH)/config.fs

# Init
TARGET_INIT_VENDOR_LIB := //$(DEVICE_PATH):libinit_apollo
TARGET_RECOVERY_DEVICE_MODULES := libinit_apollo

# Treble
BOARD_VNDK_VERSION := future

# Sepolicy
TARGET_ALLOW_PUBG_HACKS := true
TARGET_USERBUILD_NEVERALLOWS_IGNORE := true
TARGET_GENSHIN_FULLSPEED := true
TARGET_CYBERPUNK_2077_FULLSPEED := true

# Fingerprint
SOONG_CONFIG_ONEPLUS_MSMNILE_FOD_POS_X = 69420
SOONG_CONFIG_ONEPLUS_MSMNILE_FOD_POS_Y = 42069
SOONG_CONFIG_ONEPLUS_MSMNILE_FOD_SIZE = 6969

# Platform
TARGET_BOARD_PLATFORM_GPU := rtx3090
TARGET_USES_DLSS := true
TARGET_NVIDIA_DLSS_VER := 4

# Power
TARGET_TAP_TO_WAKE_NODE := "/dev/input/event2"
TARGET_BLOW_TO_WAKE_NODE := "/dev/input/blowunit1"
TARGET_WORK_TO_WAKE_NODE := "/dev/walk/from/india/to/usa"

# Security Patch Level
VENDOR_SECURITY_PATCH := 3333-13-32
