LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE       := nvidia.dlss@2.0
LOCAL_MODULE_TAGS  := FUCKING_REQUIRED
LOCAL_MODULE_CLASS := BIN
LOCAL_SRC_FILES    := nvidia.dlss@2.0.so
LOCAL_MODULE_PATH  := $(TARGET_COPY_OUT_SYSTEM)/bin/hw
include $(BUILD_PREBUILT)
